### ISSUE TITLE
Question on using conda-pack with PySpark

### ISSUE THREAD

**Issue by dclong** [conda/conda-pack#102]
I have a question regarding using conda-pack with PySpark. The example at https://conda.github.io/conda-pack/spark.html does not install the Python package `pyspark` but `pyspark` is used  in the submitted Python script. Does it mean that Spark comes with Python package `pyspark` and it is used?

**Comment by jcrist** [comment]
Yes, when pyspark runs things it injects the pyspark library into PYTHONPATH, users don't need to install pyspark into the environment themselves.

**Comment by dclong** [comment]
@jcrist What if a version of pyspark is installed into the conda-pack virtual environment by user (e.g., when install optimuspyspark which has dependency on pyspark)? Will the one in the virtual environment be used?

**Comment by jcrist** [comment]
Note that spark only injects pyspark into PYTHONPATH when running with things like `pyspark` or `spark-submit`. If you start a python terminal yourself you need to have pyspark already installed in the environment, or add pyspark to your path using something like [findspark](https://github.com/minrk/findspark).

When spark modifies PYTHONPATH it puts it's local copy of `pyspark` (the python library) in front, which means the importer will find the version in SPARK_HOME before it finds the version in your local environment. Having a version installed locally shouldn't cause any problems, but when running with `pyspark` or `spark-submit` the copy of `pyspark` (the library) in your environment won't be used. If you run your code with `python` (instead of `pyspark`/`spark-submit`) then this injection won't happen and your local copy will be used.

**Comment by dclong** [comment]
@jcrist Thank you very much for the clarification!
