### ISSUE TITLE
Damaged tar archive

### ISSUE THREAD

**Issue by Terizian** [conda/conda-pack#105]
I have created an environment on conda then installed conda-pack in the base environment using the command: `conda install -c conda-forge conda-pack` 
I then ran `conda pack -n my_env` with my environment name. However, when running the command `tar -xzf my_env.tar.gz -C my_env` I get an error saying `tar: Damaged tar archive`. 

Any idea what I can try to bypass this error? My OS is Windows 10 Home.

**Comment by rockman25** [comment]
Just ran into the same issue.

**Comment by cstutts** [comment]
I'm having the same problem. env was packaged from C:\ProgramData\Anaconda3\envs\<my_env>. Running commands in console with admin privileges.

**Comment by manuelpastor** [comment]
I have exactly the same problem

**Comment by wqshen** [comment]
same problem with the default tar.gz compress.
use -o my_env.zip is OK.

**Comment by tzo13123** [comment]
I have that problem with tar.gz but use 7zip to uncompress in Windows 10 because only can use .zip native. In Linux you can use the tar.gz. In my case I move the env (compress) into Anaconda\env directory and then uncompress. Sometimes I had problems with the kernel but only change a json in the path: share\jupyter\kernels\python3 into the env (recently uncompress) with the correct path to python.exe and works great.

**Comment by mcg1969** [comment]
I believe this has been fixed in master. Specifically, there are issues with the `.tar` format that prevent it from successfully handling hard links on Windows.

**Comment by mcg1969** [comment]
Here's the key change: https://github.com/conda/conda-pack/pull/120/commits/9c6f9423489fab262208e48393469180ddd054da#diff-505c5d0e41864bfd4666c993965620f4

**Comment by mcg1969** [comment]
(feel free to re-open if I'm wrong.)
