### ISSUE TITLE
Option for packing without creating an archive

### ISSUE THREAD

**Issue by brglng** [conda/conda-pack#157]
Hi Developers,

I would like to request a feature for providing an option for packing the environment to a directory, but not creating an archive. It would be nice if conda-pack could provide this feature. Thank you for your nice tool and greate work!

**Comment by LunarLanding** [comment]
I am interested in this too. I found conda-pack in a blog post about reducing image size for containers, and this compression-decompression is some overhead.

**Comment by mcg1969** [comment]
This is an interesting point! Question: what would be the advantage of using a directory instead of, say, an _uncompressed_ tar file?

**Comment by LunarLanding** [comment]
My reply above was in the context of making a script that would remotely build a container from an environment specification. Rather than understanding which parts of conda I could throw out to keep the environment working, I found conda-pack could do it for me. This was the silliest decision for my use case, because I don't need to move the environment to a different location, which makes activating the environment without conda simple enough (just change path, possibly run some scripts in activate.d) , and I'm not worried about depending on external repositories of packages. After all, if I ever feel like I need to freeze anything, I would freeze the container image.
As of now I'm using micromamba to install the environment. It's tiny so I don't even remove it from the container.

**Comment by brglng** [comment]
> This is an interesting point! Question: what would be the advantage of using a directory instead of, say, an _uncompressed_ tar file?

I use `conda-pack` for the packing and deployment of my Python service. My company's CI system requires putting all the files in a specific directory, and the system will then do the packaging. To meet the requirement, I have to use `conda-pack` to pack the environment and then unpack it to the directory. That'a why I would like to have this feature, so that I would not have to do the packing-unpacking.

Thank you!

**Comment by moqmar** [comment]
As this is still more of a feature request, this is still relevant as of the current main branch.

**Comment by MLaurenceFournier** [comment]
As a user, I would like to add my vote for this feature. I was about to open a similar one.

At my workplace, we use conda-pack during the preparation of installers for our clients. Just after calling conda-pack, we extract the generated archive in a temporary folder. We then let the installer generation (Inno Setup in this case), re-archive the whole project including the packed (but extracted) python environment.

Having the "--format folder" option would simplify this use case.
