### ISSUE TITLE
How can conda-pack deal with dynamic links?

### ISSUE THREAD

**Issue by peterroelants** [conda/conda-pack#161]
It is possible to include dynamic links when packaging a conda environment with `conda-pack`?

I have a multi-stage Docker build where I'm using `conda` and `conda-pack` to create a conda environment in the `continuumio/miniconda3` container, package it up with `conda-pack`, and move it to a new and clean `debian:buster-slim` container.

My conda environment contains the [`pyvips` package from the `conda-forge` channel](https://anaconda.org/conda-forge/pyvips). However when importing `pyvips` in the exported Python environment in the new container I get a `OSError: cannot load library '/opt/venv/lib/libvips.so.42': libXau.so.6: cannot open shared object file: No such file or directory` error. It seems that pyvips is dynamically linked against `libXau.so.6`.

Is there a way for `conda-pack` to deal with these Dynamic links and export them? 

(Please note, I can circumvent the issue by `apt install libxau6` in my new container. However, I would rather ensure that all dependencies are exported with `conda-pack`)

**Comment by xhochy** [comment]
There is probably no way to deal with this as the `libxau`-dependency is  not managed by conda but rather used in the build process through a CDT (e.g. `{{ cdt('xorg-x11-proto-devel') }}`). This is a system level dependency some conda packages have where it was reasoned in the build setup that these are so common and ABI-stable that it is ok for them not to be part of the environment. There are two options on how to deal with this:

 1. Rebuild `libvips` to depend on the conda-forge package that provides `libXau.so.6` so that it is conda-managed and then also included in the pack.
 2. Install `libxau6` manually as done in your workaround. As this is a system dependency and not a conda one, it is is unknown to conda-pack on how to install these. `conda-pack` has neither knowledge nor any assumptions about the package managers you use for your base distribution.

**Comment by mingwandroid** [comment]
We could at least include the rpm_name in our metadata somewhere, and then have a mechanism to look up the best equiv on your actual distro and give a recommended installation string?

**Comment by peterroelants** [comment]
Thanks for the feedback.

I tried just adding `xorg-libxau` from `conda-forge` to my environment, and this by itself seems to solve my particular problem.

**Comment by xhochy** [comment]
> We could at least include the rpm_name in our metadata somewhere, and then have a mechanism to look up the best equiv on your actual distro and give a recommended installation string?

This would mean though that we would have to persist a LIB->RPM somewhere in the package metadata though? Probably we already have the CDT name in `conda-meta/` somewhere but that wouldn't be enough information to resolve the above issue.

**Comment by mingwandroid** [comment]
Perhaps conda could use the virtual package mechanism along with run_exports in the CDT packages to create a 'shadow' dependency tree of system (centos-something) RPMs that are transitively required?

Then we could add some tooling on top of that to try to remap RPMs to whatever-distro-you-are-on (so we can use system tools, `pacman -F` or `yum whatprovides` for the backend), perhaps with a focus/filter on mapping the providers of the DSOs and exes only?
