### ISSUE TITLE
Lost my maintainer rights

### ISSUE THREAD

**Issue by xhochy** [conda/conda-pack#258]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Previously; I had maintainer rights here but the whole project got transferred to the `@conda/constructor` team. I would like to have my `conda-pack` maintenance rights back (and not be part of `constructor` ;) )

**Comment by jezdez** [comment]
For the record, conda-pack was

- previously a federated project per the governance policy (maintained by Anaconda, Inc.), like menuinst and constructor
- moved into a new constructor community project team following a discussion in a public meetings and [the issue @jaimergp created](https://github.com/conda-incubator/governance/issues/53)

All permissions for outside contributors to the conda-pack repo were retained in the transition (I did the transfer):

<img width="817" alt="CleanShot 2023-03-17 at 12 54 55@2x" src="https://user-images.githubusercontent.com/1610/225897591-cf116858-dbd2-41b4-8612-47dcf357c7e3.png">

As you can see, you have write permissions as an outside collaborator.

If you'd like to gain maintenance permissions (which is more than what the governance policy dictates, which mentions "write access"), please ask the @conda/constructor team to approve you being added to that team, since [community project teams are responsible for self-governance](https://github.com/conda-incubator/governance#nominate-new-member-of-a-community-project-team).

**Comment by xhochy** [comment]
One confusing thing for me has been that I couldn't merge the PR once `dbast` approved. He was the sole other person I interacted here in the recent past. This led me to infer that I had no write rights anymore. Checking exactly, I think I have sufficient rights on this repository, except that I should be listed in `CODEOWNERS`.

**Comment by xhochy** [comment]
Reopening this as I would expect to be able to merge https://github.com/conda/conda-pack/pull/256

**Comment by jezdez** [comment]
@xhochy You have maintainer permissions: not sure if this was fixed by someone or what the status is about this.

<img width="829" alt="CleanShot 2023-08-15 at 16 52 44@2x" src="https://github.com/conda/conda-pack/assets/1610/9e282657-4930-4561-9ca5-a3a646772a9e">

**Comment by jezdez** [comment]
Sorry about that @xhochy!
