### ISSUE TITLE
[Feature Request] Pack only what is NEEDED

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-pack#29]
User story:

I am a C/C++ developer and I use a conda environment to get my dependencies (mostly libraries). My code generates several binaries and shared libraries. Now, when I want to run my binary in production, it's not efficient to create the entire environment again, because:
- My binary could just be depending on a certain number of shared libraries, not all. For example, I might be using the unzip conda package to unzip something, but I don't need the unzip binary for my final binary. Another example is I might use the gxx_linux-64 package to compile my binary, but I don't need the compiler during the execution of the binary. I just need libstdcxx-ng.
- My binary could be linking to some libraries statically, so they are not needed at runtime. Example: googletest/gmock/googlebenchmark for tests

Sure, a recommended way for the user would be to create a conda package every time and then conda install it. But creating a conda package on the dev machine and then deploying it in production would require additional time to scp the binary to a channel, and then index it.

Another way would be to maintain an environment.yaml file and use it to deploy the binary. But that suffers from the same problem of sifting through your requirements to see what is actually NEEDED.

A simple way to go about this would be to recursively look at the NEEDED ELF section in the binary/shared libraries that I created and pack only those packages which provided the shared libraries I depend on (from the conda env prefix). Conda build has a function for the reverse lookup: https://github.com/conda/conda-build/blob/3.10.9/conda_build/inspect_pkg.py#L35-L43

The cli might look something like:
```
conda-pack /path/to/build/folder/containing/my/project/binaries/or/libraries --needed-only
```

This would pack all the requirements really needed, and during `conda-unpack`, in addition to what it already does right now, it would also invoke patchelf on my binaries/shared libraries to fix the RPATHs to point to the new location.

**Comment by jcrist** [comment]
My immediate thought is that this is out of scope for `conda-pack`. Conda-pack is for taking an existing conda environment, and packaging it for redistribution. Nothing more.

> Sure, a recommended way for the user would be to create a conda package every time and then conda install it. But creating a conda package on the dev machine and then deploying it in production would require additional time to scp the binary to a channel, and then index it

You don't need to push it to anaconda.org, you can also install the built `bz2` directly (`conda install path_to.tar.bz2`). A workflow might be to build a conda package, build a prod environment from that package, and then package that environment. I wouldn't try to replicate some of conda build (ELF inspection) outside of conda build, I'd just use conda build. This maintains the existing separation of concerns (conda-build builds conda packages, conda-pack packages conda environments).

> The cli might look something like:

If you wanted to make a new tool to do this, you could make use of `conda-pack`. Since it doesn't rely on importing `conda` (and is designed to also have a python api), you could `import conda_pack` and do the package filtering yourself with the `include`/`exclude` methods (see api docs: https://conda.github.io/conda-pack/api.html).

**Comment by jcrist** [comment]
Closing for now. Feel free to reopen if you disagree with any of the above.
