### ISSUE TITLE
Question about conda-meta exclusion

### ISSUE THREAD

**Issue by parente** [conda/conda-pack#32]
I notice that I can create a non-base conda environment that includes `conda>4.5`, pack this environment, and later unpack it without issue. 

```
conda create -n pack-base python=3 conda pip

# normal conda output removed for brevity ...

conda pack -n pack-base --arcroot pack-base
Collecting packages...
Packing environment at '/Users/parente/miniconda3/envs/pack-base' to 'pack-base.tar.gz'
[########################################] | 100% Completed |  5.0s

# on another host
tar xzf pack-base.tar.gz -C tmp
source /tmp/pack-base/bin/activate
conda unpack
```

I notice that `conda-meta` is not included by default in the packed environment, which means `conda list` (and maybe other conda commands?) does not function after unpacking.

```
conda list

EnvironmentLocationNotFound: Not a conda environment: /tmp/pack-base
```

However, if I manually add the `conda-meta` from the original environment to the tarball so that it's available later, `conda` seems to work properly after unpacking. So much so that I can list, install, uninstall, etc. packages in that unpacked environment.

Could you explain why `conda-meta` is not included in the tarball generated by `conda pack`? I'm guessing there's a good reason, and that if I add `conda` and `conda-meta` to my packed envs, I'll hit some surprise down the line that I've not discovered yet.

I ask because I have an interest in packing and distributing environments in which `conda` itself functions.

**Comment by nehaljwani** [comment]
Till this feature becomes part of conda-pack (if at all) you can use [constructor](https://github.com/conda/constructor).

**Comment by ericdill** [comment]
Constructor does not support noarch packages. Having some inside knowledge about what @parente is working on (since I helped build the system he's working on) I am pretty confident he's trying to add support for noarch packages by using conda-pack.

**Comment by jcrist** [comment]
Apologies for the delay here, still catching up after vacation.

The `conda-meta` directory (and a few other conda-specific things) were stripped from the environment because the intent of this project was to distribute conda environments to locations where conda wasn't already installed (my use case specifically was deployment on YARN). Since this doesn't handle the root environment, and conda can only be installed in the root environment, this can't be used to distribute environments that contain conda. And if a machine already has conda installed on it, it seems cleaner and more robust to try and recreate the environment using something like `conda env`.

That said, I don't see any harm in not stripping out `conda-meta`. The file sizes are small and should compress well, and users can always filter it out if needed. A few potential issues that come to mind (untested):

- We also strip out `conda`, `activate`, and `deactivate` from `/bin`, and replace `activate` and `deactivate` with our own versions. This *may* break workflows using standard conda tools, or it may not. Unsure.

- The `conda-meta` files include a couple absolute paths (mostly package cache information). I *think* these are harmless to copy over (conda is fairly robust to malformed package caches), but the best thing to do would probably be to fix `link.type` in all files to be `copy` (same for `pathtype` for each path record), and replace the absolute paths with empty strings or some bogus string (to strip the user information).

I don't have time currently to test these issues out, but if you do @parente I'd accept and review a PR.

**Comment by parente** [comment]
Couple thoughts:

> Since this doesn't handle the root environment, and conda can only be installed in the root environment, this can't be used to distribute environments that contain conda.

Whether intentional or not, with conda 4.5.x, I *can* install conda in a non-root/base environment. conda no longer stops me with the error about it only working in root environments. It turns out I can also conda-pack such an environment, move it, conda-unpack it, and then use `conda` successfully from that new location to install new packages. The only thing that doesn't work is `conda list` because of the lack of `conda-meta`. (See description for the exact commands I've run.)

> We also strip out conda, activate, and deactivate from /bin, and replace activate and deactivate with our own versions. This may break workflows using standard conda tools, or it may not. Unsure.

They all seem to work fine in my initial testing with numerous environment definitions on Linux machines.

> I don't have time currently to test these issues out, but if you do @parente I'd accept and review a PR.

If I don't hit any showstoppers after some more internal testing, I'm happy to submit a PR to get `conda-meta` cleaned and included.

**Comment by jcrist** [comment]
> Whether intentional or not, with conda 4.5.x, I can install conda in a non-root/base environment.

Ah, good to know (I should really read the conda release notes). In this case, I think the todo list for this functionality is:

- Stop removing `conda` and `conda-meta` from the environment (looks like new conda doesn't put a `conda` file in `/bin` unless conda was explicitly installed in the environment.
- Rewrite the `json` files in `conda-meta` to fix the absolute path and link information
- Tests (if you can't figure out an easy way to test this functionality, I'd be happy to handle this).

Thanks for looking in to this!

**Comment by parente** [comment]
@jcrist Small FYI, PR #35 seems to prevent packed environments from including conda now:

```
08:45:37 CondaPackError: 
08:45:37 Files managed by conda were found to have been deleted/overwritten in the
08:45:37 following packages:
08:45:37 
08:45:37 - conda='4.5.10'
08:45:37 
08:45:37 This is usually due to `pip` uninstalling or clobbering conda managed files,
08:45:37 resulting in an inconsistent environment. Please check your environment for
08:45:37 conda/pip conflicts using `conda list`, and fix the environment by ensuring
08:45:37 only one version of each package is installed (conda preferred).
```

I know this was not officially supported yet, and it's on me to get back to you with a PR to make it official (still experimenting). Just a heads-up.

**Comment by jcrist** [comment]
Oop, sorry about that. It's because we're dropping `bin/conda`, `bin/activate`, and `bin/deactivate` (the former because in older environments it's a thin wrapper shelling out to the main conda (not an issue in recently created environments), the latter 2 because we override them with our own implementations) prior to checking for missing files.

It occurred to me that adding this feature would be pretty quick, so I pushed a quick WIP to #37 (apologies if you'd already started work on this). I don't plan on pushing further on this until further manual testing is done - if you could give that PR a try and let me know if it works for you that'd be great.
