### ISSUE TITLE
Compare files from `conda-meta` with files in environment directory to catch manual uninstalls

### ISSUE THREAD

**Issue by bharathguvvala** [conda/conda-pack#34]
The following environment when packed doesn't resolve to the right version of packages in the final unpacked environment. _Spacy_ depends on a different version of _thinc_ specified in the environment file creating a conflict and hence finally being resolved by _pip_ (_thinc : 6.10.3_). But the unpacked environment still has _thinc : 6.5.2_. I have packed the conda env with unmanaged=True. Can someone help explain this behaviour?

<pre><code>channels:
 - conda-forge
 - defaults
dependencies:
 - thinc=6.5.2=py27_0
 - pip:
   - spacy==2.0.9
</pre></code>

**Comment by jcrist** [comment]
Hmmm, this is a bug, but it can be avoided by not specifying `thinc` in dependencies (since the pip installation of `spacy` will overwrite the existing `thinc` install). Why are you using `spacy` from pip instead of from conda-forge?

Basically, what's happening here is:

- `conda-env` builds a new environment and first installs all the conda packages. This pulls in `thinc=6.5.2`.
- `conda-env` then installs `pip` packages, which results in `pip` uninstalling `thinc=6.5.2` and replacing it with `thinc=6.10.3` from `pypi`. But since `pip` did the uninstall, the metadata for `thinc` is still in the `conda-meta` directory (`pip` doesn't play 100% well with `conda`).
- `conda-pack` packages the environment by reading in the metadata from the `conda-meta` directory, which still includes the information for `thinc=6.5.2`. It then crawls the directory and finds `thinc=6.10.3` from pypi and also includes that.

We should filter the files found from collecting `conda-meta` with those actually in the environment directory to catch issues of pip installs breaking stuff.

However, this can be avoided by having your `pip` install never uninstall packages (in this case, remove `thinc` from dependencies).

**Comment by bharathguvvala** [comment]
Thanks @jcrist for the explanation. Can I raise a PR with the fix for this? Agreed that this can be avoided by proactively pruning out conflicts from the environment.yaml itself, but with the environment already being created should the conda-pack fail fast for now in such case until the fix has been made to stop the user from packing the environment with incorrect set of packages?

**Comment by jcrist** [comment]
Hmmm, this is a bit trickier than I originally thought. The main issue here is that manual changes to the environment may not change the total set of files, and instead just be small edits/replacement of individual files. In this case looking for missing conda files wouldn't catch these issues, as the sets would be identical. Instead we should check overwrites either by:

- Hashing the file and comparing to the hash in the conda metadata. This is further complicated because older versions of the metadata don't include file hashes.
- Looking at the hardlink status of the file to see if it still points to the package cache (only would work for files that are hardlinked, but would be faster than hashing).

This requires a larger refactor than I expected it would. You are welcome to work on it if you want, but it's not an easy problem. I'll probably have more time to work on this late next week.

**Comment by bharathguvvala** [comment]
Sure @jcrist . I realize this is a complicated problem. I'll wait for you to work upon it.

**Comment by jcrist** [comment]
This should be fixed in #35.
