### ISSUE TITLE
Published documentation is outdated

### ISSUE THREAD

**Issue by saraedum** [conda/conda-pack#352]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The documentation at https://conda.github.io/conda-pack/index.html seems quite outdated.

For example https://conda.github.io/conda-pack/index.html#use-cases contains 5 bullet points but there should be 6 since the commit from "Feb 8, 2022".

Btw., it says © 2017 at the bottom but that's just the configuration for the documentation build.

**Comment by jezdez** [comment]
As a first step, I'd replace the used github action with the one maintained by GitHub now, since that doesn't require a special token anymore (which is likely the cause of the build failure): https://github.com/actions/upload-pages-artifact (which also refers to https://github.com/actions/deploy-pages)
