### ISSUE TITLE
Install conda in a temporary directory if missing

### ISSUE THREAD

**Issue by superbobry** [conda/conda-pack#43]
`CondaCreator` component of [knit](https://github.com/dask/knit) had a nice feature: it installed Miniconda if it was not available in $PATH. One could argue that installing conda is easy and that the user would probably want to do it anyway, but I think it is a reasonable and user-friendly default behaviour despite that.

Would you like to see this implemented in conda-pack?

**Comment by jcrist** [comment]
Since conda-pack is for packaging already created conda environments only, it doesn't really make sense to install our own version - the user wouldn't be using it if they didn't already have conda installed.

I'm also against automatic behaviors like this, and think that choice was a poor one for knit because:
- Installing it is expensive (long download, large resources)
- It's potentially error prone (what if you're behind a proxy?)
- The install is unmanaged by the user (how can they update conda later on? I certainly don't want to manage updating conda from within conda-pack)
- It makes things more complicated. Where do you store our local conda install? Is this configurable? What if the user installs their own conda version later?

**Comment by superbobry** [comment]
Thanks for the reply @jcrist. I agree with all of your points. Initial UX does not outweigh all the cons.
