### ISSUE TITLE
Will the conda-unpack not replace the #!/usr/bin/env python in executables in an environment?

### ISSUE THREAD

**Issue by bharathguvvala** [conda/conda-pack#44]
I have an environment which has gunicorn for eg. installed in it. When I run conda-unpack after extracting the packed environment the gunicorn executable still has "#!/usr/bin/env python" as a shebang line. Shouldn't it be "#!/usr/bin/env <env_path>/bin/python" ? Should we always run the executables by activating the environment? What if I want to fork the gunicorn process from within another program. Is there a way to programmatically activate an environment?

**Comment by jcrist** [comment]
Conda environments in general are designed to be activated before use (some packages require activate/deactivate hooks to function properly). In this case we did the easy thing and rewrote all shebangs to use `/usr/bin/env` so that they work regardless of `conda-unpack` being run, provided that the environment is activated beforehand. We *could* make `conda-unpack` also fix these, but I'm not sure that's necessary - in general you should always activate the environment before use.

If you don't want to activate the environment, right now you can call the script with python explicitly - 

```
<env_path>/bin/python <env_path>/bin/gunicorn ...
```

> What if I want to fork the gunicorn process from within another program. Is there a way to programmatically activate an environment?

I'm not sure what you mean by this. Activating an environment is mostly just putting the environment on your `PATH`, if you can source the script in your executable (e.g. as part of an executable shell script), then the user doesn't need to be aware of the environment at all:

```bash
#!/usr/bin/env sh
# Activate the environment and start your application
source <env_path>/bin/activate
start-my-app
```

**Comment by mcg1969** [comment]
Yes, conda environments assume they are fully activated before any script or executable is called within them. The behavior that occurs if you directly call scripts or executables without activation is not well defined.

At the very minimum, all programs inside the environment need to be able to assume that the PATH includes the conda environment. Otherwise, there is a chance that if program A calls program B as a subprocess, program B might not see the proper PATH.

But some environments also have activation scripts in them. These scripts can perform arbitrary tasks upon activation, but the most common and useful task is to set environment variables. If you directly call programs inside an environment without activation, those environment variables will not be set.
