### ISSUE TITLE
Difference to `constructor`

### ISSUE THREAD

**Issue by certik** [conda/conda-pack#45]
What's the difference between `conda-pack` and [constructor](https://github.com/conda/constructor)? When would you use one and when the other? What are the pros and cons of each?

**Comment by certik** [comment]
I was told that `constructor` is not maintained. So that leaves `conda-pack` as the only viable option to create an installer.

**Comment by mingwandroid** [comment]
It is maintained.

**Comment by certik** [comment]
@mingwandroid oh, my apologies then. I'll give it a shot also.

**Comment by scopatz** [comment]
Hmm my understanding, was that it wasn't good for us to use conda-constructor

**Comment by mingwandroid** [comment]
In what regards? We use it extensively, Miniconda and Anaconda installers are all built on it and I don't see that changing anytime soon.

Now would I recommend constructor over competing technologies? From a clean slate, no way (it has 3 basically independent back ends for a start) but since it exists and works it serves a useful purpose.

**Comment by scopatz** [comment]
My understanding is that constructor does not work for noarch packages, and at least for conda-forge [we were asked not to use constructor](https://github.com/conda-forge/conda-forge.github.io/issues/90#issuecomment-356625940). This is totally fine, but my general impression is that conda-constructor is sort of an internal tool.

**Comment by jcrist** [comment]
@scopatz , was that the correct link? That post is about not using constructor to create a conda-forge-only miniconda-like distro, not about not using constructor at all.

Yes, constructor doesn't currently work for noarch packages. It also has a different intended use case than `conda-pack`. To reiterate what I said above https://github.com/conda/conda-pack/issues/45#issuecomment-421764654, this project was intended mainly for distributing Python environments in deployment scenarios (mainly for clusters, YARN specifically, but there are other use cases) - `constructor` is for creating installers, which may be more user facing.

**Comment by scopatz** [comment]
Right, so the two big blockers for use for conda-constructor are the noarch issue and being asked not to use it for conda-forge (which again, I am fine with and don't want to relitigate here :smile:).

**Comment by certik** [comment]
@scopatz, @jcrist, @mingwandroid I am just really confused. I am looking for a tool that allows me to create 3 tarballs (one for each Linux, Mac, and Windows), that I can move over to a computer without an internet connection that will unpack, and allow me to run our production application. It doesn't need to install Conda, but it needs to be easy enough to use for users of the application.

What would you recommend I use?

**Comment by msarahan** [comment]
That seems like a good use for conda-pack, more than constructor.

**Comment by jcrist** [comment]
> That seems like a good use for conda-pack, more than constructor.

Agreed, depending on sophistication of the users. If constructor supported all the packages you needed (e.g. no noarch packages) I might recommend that over conda-pack, as it's only a single step (run the installer) rather than unpack to a directory, activate the environment, and (optionally) run the `conda-unpack` script. But yes, this is a valid usecase for `conda-pack`.
